name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub ke runner par apna code lekar aao
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. GitHub Container Registry (GHCR) par login karo
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Docker Image build aur push karo automation se
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/hammad014-wq/premium-weather-app:latest
            ghcr.io/hammad014-wq/premium-weather-app:${{ github.sha }}